new format for hash files: *.sig => *.hash, no SHA1SUM, allow automatic hash checking
no SHA1SUM rational: SHA1SUM has been broken for over 12 years.

automatic hash checking rational: you don't need to eyeball it, though you still can

*.sig => *.hash rational:

- *.sig are a convention GPG uses for detached signatures
- people familiar with the convention have no reason to treat it as anything but a detached sig

  - if you think *.sig is a detached signature gpg --verify doesn't do what you
    think it does
  - in particular it doesn't check the original file, it only checks the clear
    signature
  - you don't always get a warning about this
  - you may not realize there are text instructions inside the *.sig file
  - if you don't read the instructions, you'll miss the fact that there are two
    verification steps needed.

diff --git a/bin/iso-verify b/bin/iso-verify
--- a/bin/iso-verify
+++ b/bin/iso-verify
@@ -15,7 +15,7 @@ info() { echo "INFO [$(basename $0)]: $@"; }
 usage() {
 cat<<EOF
 Syntax: $0 isodir version appname
-Verify ISO by getting .sig and verifying (skipped if .sig exists)
+Verify ISO by getting .hash and verifying (skipped if .hash exists)
 
 Arguments::
 
@@ -43,20 +43,20 @@ version=$2
 appname=$3
 
 isofile=turnkey-$appname-$version.iso
-sigfile=turnkey-$appname-$version.iso.sig
-sigpath=$isodir/$sigfile
+hashfile=turnkey-$appname-$version.iso.hash
+hashpath=$isodir/$hashfile
 
-if [ ! -e $sigpath ]; then
-    src=http://releases.turnkeylinux.org/turnkey-$appname/$version/$sigfile
-    wget --read-timeout=60 --tries=10 $src -O $sigpath
+if [ ! -e $hashpath ]; then
+    src=http://releases.turnkeylinux.org/turnkey-$appname/$version/$hashfile
+    wget --read-timeout=60 --tries=10 $src -O $hashpath
 else
-    info "$sigfile already exists, skipping..."
+    info "$hashfile already exists, skipping..."
     exit 0
 fi
 
-if ! $BT/bin/signature-verify $isodir/$isofile $sigpath; then
+if ! $BT/bin/signature-verify $isodir/$isofile $hashpath; then
     mv $isodir/$isofile $isodir/$isofile.corrupt
-    rm $sigpath
-    fatal "$sigfile verification failed"
+    rm $hashpath
+    fatal "$hashfile verification failed"
 fi
 
diff --git a/bin/signature-verify b/bin/signature-verify
--- a/bin/signature-verify
+++ b/bin/signature-verify
@@ -14,13 +14,13 @@ info() { echo "INFO [$(basename $0)]: $@"; }
 
 usage() {
 cat<<EOF
-Syntax: $0 isofile sigfile
+Syntax: $0 isofile hashfile
 Verify GPG signature and checksum
 
 Arguments::
 
     isofile         - path to iso file
-    sigfile         - path to sig file
+    hashfile        - path to hash file
 
 Environment::
 
@@ -35,7 +35,7 @@ if [[ "$#" != "2" ]]; then
 fi
 
 isopath=$1
-sigpath=$2
+hashpath=$2
 
 if ! gpg --list-keys $BT_GPGKEY 2>&1 >/dev/null; then
     gpg --keyserver hkp://pool.sks-keyservers.net --recv-keys 0x$BT_GPGKEY
@@ -43,13 +43,13 @@ fi
 
 
 info "verifying gpg signature"
-if ! gpg --verify $sigpath; then
-    fatal "$sigpath gpg verification failed"
+if ! gpg --verify $hashpath; then
+    fatal "$hashpath gpg verification failed"
 fi
 
 info "verifying checksum"
-sum1=$(sha1sum $isopath | cut -d " " -f 1)
-sum2=$(grep -A 1 sha1sum $sigpath | tail -n 1 | sed "s/^ *//")
+sum1=$(sha256sum $isopath | cut -d " " -f 1)
+sum2=$(grep -A 1 sha256sum $hashpath | head -n 2 | tail -n 1 | sed "s/^ *//; s/ .*//")
 if [ ! "$sum1" == "$sum2" ]; then
     fatal "$isopath checksum verification failed"
 fi
