attempt download from s3 build bucket if ISO not found on mirror

diff --git a/bin/iso-download b/bin/iso-download
--- a/bin/iso-download
+++ b/bin/iso-download
@@ -1,5 +1,5 @@
 #!/bin/bash -e
-# Copyright (c) 2011-2015 TurnKey GNU/Linux - http://www.turnkeylinux.org
+# Copyright (c) 2011-2018 TurnKey GNU/Linux - https://www.turnkeylinux.org
 # 
 # This file is part of buildtasks.
 # 
@@ -37,11 +37,15 @@ appname=$3
 isofile=turnkey-$appname-$version.iso
 
 if [ -e $outdir/$isofile ]; then
-    info "$isofile already exists, skipping..."
+    info "$isofile already exists, skipping download..."
     exit 0
 fi
 
-mkdir -p $outdir
-images="http://mirror.turnkeylinux.org/turnkeylinux/images"
-wget --read-timeout=60 --tries=10 $images/iso/$isofile -O $outdir/$isofile
+. $BT_CONFIG/aws.cfg &>/dev/null || true
 
+mkdir -p $outdir
+mirror_images="http://mirror.turnkeylinux.org/turnkeylinux/images"
+bucket_images="s3://turnkeylinux-builds/images"
+wget --read-timeout=60 --tries=10 $mirror_images/iso/$isofile -O $outdir/$isofile \
+    || aws s3 cp $bucket_images/iso/$isofile $outdir/$isofile \
+    || fatal "$isofile download failed"
diff --git a/bin/iso-verify b/bin/iso-verify
--- a/bin/iso-verify
+++ b/bin/iso-verify
@@ -1,5 +1,5 @@
 #!/bin/bash -e
-# Copyright (c) 2011-2015 TurnKey GNU/Linux - http://www.turnkeylinux.org
+# Copyright (c) 2011-2018 TurnKey GNU/Linux - https://www.turnkeylinux.org
 # 
 # This file is part of buildtasks.
 # 
@@ -46,12 +46,16 @@ isofile=turnkey-$appname-$version.iso
 hashfile=turnkey-$appname-$version.iso.hash
 hashpath=$isodir/$hashfile
 
+. $BT_CONFIG/aws.cfg &>/dev/null || true
+
 if [ ! -e $hashpath ]; then
-    src=http://releases.turnkeylinux.org/turnkey-$appname/$version/$hashfile
-    wget --read-timeout=60 --tries=10 $src -O $hashpath
+    mirror_src=http://releases.turnkeylinux.org/turnkey-$appname/$version/$hashfile
+    bucket_src=s3://turnkeylinux-builds/metadata/$hashfile
+    wget --read-timeout=60 --tries=10 $mirror_src -O $hashpath \
+        || aws s3 cp $bucket_src $hashpath \
+        || fatal "$hashfile download failed"
 else
-    info "$hashfile already exists, skipping..."
-    exit 0
+    info "$hashfile already exists, skipping download..."
 fi
 
 if ! $BT/bin/signature-verify $isodir/$isofile $hashpath; then
@@ -59,4 +63,3 @@ if ! $BT/bin/signature-verify $isodir/$isofile $hashpath; then
     rm $hashpath
     fatal "$hashfile verification failed"
 fi
-
diff --git a/bin/signature-verify b/bin/signature-verify
--- a/bin/signature-verify
+++ b/bin/signature-verify
@@ -1,5 +1,5 @@
 #!/bin/bash -e
-# Copyright (c) 2011-2015 TurnKey GNU/Linux - http://www.turnkeylinux.org
+# Copyright (c) 2011-2018 TurnKey GNU/Linux - https://www.turnkeylinux.org
 # 
 # This file is part of buildtasks.
 # 
@@ -10,6 +10,7 @@
 
 
 fatal() { echo "FATAL [$(basename $0)]: $@" 1>&2; exit 1; }
+warning() { echo "WARNING [$(basename $0)]: $@"; }
 info() { echo "INFO [$(basename $0)]: $@"; }
 
 usage() {
@@ -41,10 +42,16 @@ if ! gpg --list-keys $BT_GPGKEY 2>&1 >/dev/null; then
     gpg --keyserver hkp://pool.sks-keyservers.net --recv-keys 0x$BT_GPGKEY
 fi
 
-
 info "verifying gpg signature"
-if ! gpg --verify $hashpath; then
-    fatal "$hashpath gpg verification failed"
+if ! output=$(gpg --verify $hashpath 2>&1); then
+    if [ "${output%%$'\n'*}" = "gpg: no valid OpenPGP data found." ]; then
+        warning "hash file is not signed by gpg - this is expected if building locally and/or the hash file is unsigned"
+    else
+        echo "$output"
+        fatal "$hashpath gpg verification failed"
+    fi
+else
+    echo "$output"
 fi
 
 info "verifying checksum"
