bin/iso-download - ensure it tries bucket when 404 from mirror

diff --git a/bin/iso-download b/bin/iso-download
--- a/bin/iso-download
+++ b/bin/iso-download
@@ -46,6 +46,9 @@ fi
 mkdir -p $outdir
 mirror_images="http://mirror.turnkeylinux.org/turnkeylinux/images"
 bucket_images="s3://turnkeylinux-builds/images"
-wget --read-timeout=60 --tries=10 $mirror_images/iso/$isofile -O $outdir/$isofile \
-    || aws s3 cp $bucket_images/iso/$isofile $outdir/$isofile \
-    || fatal "$isofile download failed"
+if ! wget --read-timeout=60 --tries=10 $mirror_images/iso/$isofile \
+        -O $outdir/$isofile; then
+    if ! aws s3 cp $bucket_images/iso/$isofile $outdir/$isofile; then
+        fatal "$isofile download failed"
+    fi
+fi
