Check if bootstrap is already unpacked to fab/bootstraps/ dir

diff --git a/bin/signature-verify b/bin/signature-verify
--- a/bin/signature-verify
+++ b/bin/signature-verify
@@ -1,5 +1,5 @@
 #!/bin/bash -e
-# Copyright (c) 2011-2018 TurnKey GNU/Linux - https://www.turnkeylinux.org
+# Copyright (c) 2011-2026 TurnKey GNU/Linux - https://www.turnkeylinux.org
 # 
 # This file is part of buildtasks.
 # 
@@ -8,14 +8,14 @@
 # Free Software Foundation; either version 3 of the License, or (at your
 # option) any later version.
 
-
-fatal() { echo "FATAL [$(basename $0)]: $@" 1>&2; exit 1; }
-warning() { echo "WARNING [$(basename $0)]: $@"; }
-info() { echo "INFO [$(basename $0)]: $@"; }
+APP=$(basename "$0")
+fatal() { echo "FATAL [$APP]: $*" 1>&2; exit 1; }
+warning() { echo "WARNING [$APP]: $*"; }
+info() { echo "INFO [$APP]: $*"; }
 
 usage() {
 cat<<EOF
-Syntax: $0 file hashfile [-f|--force-gpg]
+Syntax: $APP file hashfile [-f|--force-gpg]
 Verify GPG signature of hashfile and checksum of file (from hashfile)
 
 Arguments::
@@ -27,12 +27,18 @@ Options::
 
     -f|--force-gpg  - Force GPG signiture check of hash file. Exit with
                       non-zero exit code if not signed by BT_GPGKEY.
-                      Default is to only display a warning and continue.
+                      If the file is not signed, default is to only display a
+                      warning and continue. If the file is signed a GPG check
+                      will always occur.
     -h|--help       - Display this usage info and exit.
 
 Environment::
 
-    BT_GPGKEY       - [Required] GPG key id used to sign the hash file.
+    BT_GPGKEY       - GPG key id used to sign the hash file. Required if
+                      BT_GPGFILE not set.
+    BT_GPGFILE      - GPG file to use; may be local file or remote https url.
+                      Required if BT_GPGKEY not set. Will override BT_GPGKEY
+                      if both set.
     BT_DEBUG        - Make output verbose.
 
 EOF
@@ -41,7 +47,34 @@ exit 1
 
 [[ -z "$BT_DEBUG" ]] || set -x
 
-unset filepath hashpath
+BT=$(dirname $(readlink -f $0))
+BT_CONFIG="$BT/config/common.cfg"
+if [[ -f "$BT_CONFIG" ]]; then
+    source "$BT_CONFIG"
+else
+    warning "config file not found at $BT_CONFIG; attempting to continue"
+fi
+
+if [[ -n "$BT_GPGFILE" ]]; then
+    info "BT_GPGFILE set ($BT_GPGFILE)"
+    if [[ "$BT_GPGFILE" == "http"* ]]; then
+        if [[ "$BT_GPGFILE" == "https"* ]]; then
+            fatal "BT_GPGFILE url must be https ($BT_GPGFILE)"
+        fi
+
+    else
+        
+elif [[ -n "" ]]; then
+
+        if ! gpg --list-keys $BT_GPGKEY 2>&1 >/dev/null; then
+else
+    fatal "either BT_GPGFILE or BT_GPGKEY must be set"
+fi
+
+    
+
+
+unset filepath hashpath force_gpg
 while [ "$1" != "" ]; do
     case $1 in
         --help|-h)
@@ -60,14 +93,27 @@ while [ "$1" != "" ]; do
     shift
 done
 
-[[ -n "$filepath" ]] && [[ -n "$hashpath" ]] \
-    || fatal "file and hashfile must be set. See '--help' for more info."
+if [[ -z "$filepath" ]] || [[ -z "$hashpath" ]]; then
+    fatal "file and hashfile must be set. See '--help' for more info."
+elif [[ ! -f "$filepath" ]] || [[ ! -f "$hashpath" ]]; then
+    fatal "file &/or hashfile not found ($filepath / $hashpath)"
+fi
+
+if ! grep -q "BEGIN PGP SIGNED MESSAGE" "$hashpath"; then
+    info "$hashpath is not signed"
+    if [[ "$force_gpg" == "yes" ]]; then
+        fatal "'--force-gpg' was used but the hash file is not signed"
+    fi
+else
+    # set force_gpg so signed hash files are always verified
+    force_gpg="yes"
 
 if ! gpg --list-keys $BT_GPGKEY 2>&1 >/dev/null; then
     info "Downloading GPG key: $BT_GPGKEY."
     if ! gpg --keyserver hkps://keyserver.ubuntu.com --recv-keys $BT_GPGKEY; then
         warning "importing from keyserver.ubuntu.com failed; trying alternate."
-        wget -O /tmp/$BT_GPGKEY.asc https://www.turnkeylinux.org/$BT_GPGKEY.asc \
+        if wget -O /tmp/$BT_GPGKEY.asc \
+            https://www.turnkeylinux.org/$BT_GPGKEY.asc
             || fatal "failed to download GPG key $BT_GPGKEY."
         gpg --import /tmp/$BT_GPGKEY.asc || fatal "alternate import failed."
         rm -f /tmp/$BT_GPGKEY.asc*
diff --git a/bt-iso b/bt-iso
--- a/bt-iso
+++ b/bt-iso
@@ -144,18 +144,21 @@ build_bootstrap() {
         fi
     fi
     info "preparing bootstrap for app building"
-    if [[ "$built" == "yes" ]]; then
-        rsync --delete -Hac "$BOOTSTRAP_SRC"/build/bootstrap/ \
-            "$BOOTSTRAP_PATH/"
-    else
-        mkdir -p "$BOOTSTRAP_PATH"
-        tar -zxf "$BOOTSTRAP_TAR" -C "$BOOTSTRAP_PATH"
+    if [[ ! -f "$BOOTSTRAP_PATH/bin/bash" ]]; then
+        if [[ "$built" == "yes" ]]; then
+            rsync --delete -Hac "$BOOTSTRAP_SRC"/build/bootstrap/ \
+                "$BOOTSTRAP_PATH/"
+        else
+            mkdir -p "$BOOTSTRAP_PATH"
+            tar -zxf "$BOOTSTRAP_TAR" -C "$BOOTSTRAP_PATH"
+        fi
     fi
-    # create symlinks so bin/generate-buildenv completes successfully
-    ln -s "$BT_BUILDS/bootstrap/$BOOTSTRAP_NAME.tar.gz" \
-        "$(dirname "$BOOTSTRAP_PATH")/$BOOTSTRAP_NAME.tar.gz"
-    ln -s "$BT_BUILDS/bootstrap/$BOOTSTRAP_NAME.tar.gz.hash" \
-        "$(dirname "$BOOTSTRAP_PATH")"/"$BOOTSTRAP_NAME.tar.gz.hash"
+    # symlink to tar and hash file if needed so generate-buildenv doesn't fail
+    fab_dir="$(dirname "$BOOTSTRAP_PATH")"
+    for _bootstrap in "$BOOTSTRAP_TAR" "$BOOTSTRAP_TAR.hash"; do
+        [[ ! -f "$fab_dir/$(basename "$_bootstrap")" ]] || continue
+        ln -s "$_bootstrap" "$fab_dir/$(basename "$_bootstrap")"
+    done
 }
 
 export WEBDRIVER_CONNECT_ATTEMPTS=${WEBDRIVER_CONNECT_ATTEMPTS:-200}
